# checkpoint
checkpoint: 
  use: False
  checkpoint_path: './checkpoint'

# model
model_args: 
  input_channel: 3
  num_class: 4
  
# optimizer argument
optimizer: 
  select_optim: 'SGD'
  optimizer_sgd: 
    lr: 0.05
    weight_decay: 0.0001
    momentum: 0.5

  optimizer_adam: 
    lr: 0.05
    weight_decay: 0.0001